import { AI_TTL } from '../config/constants.js';
import { env } from '../config/env.js';
import { getRepository } from '../lib/repository/index.js';
import { logger } from '../lib/logger.js';

const aiCache = {};
const aiInflight = {};
const analysisLogger = logger.child({ component: 'analysis-service', provider: 'Anthropic' });

function isFresh(cache, key, ttl) {
  return cache[key] && (Date.now() - cache[key].ts < ttl);
}

function cloneAnalysisData(data) {
  return data ? JSON.parse(JSON.stringify(data)) : null;
}

function getConfidenceBand(confidence) {
  if (confidence >= 82) return 'High conviction, still market-sensitive';
  if (confidence >= 68) return 'Measured edge with known uncertainty';
  return 'Lean only — variance remains high';
}

function getUncertaintyNote(analysis) {
  const riskFactor = safeRiskFactor(analysis);
  if (riskFactor) return riskFactor;
  if ((analysis.confidence || 0) >= 82) return 'Even strong model leans can be overturned by late news, lineup changes, or price movement.';
  if ((analysis.confidence || 0) >= 68) return 'Treat this as an informed edge, not a guaranteed result — matchup variance still matters.';
  return 'This reads as a lower-conviction lean and should be weighed carefully against price and late context.';
}

function safeRiskFactor(analysis) {
  const risk = safeArray(analysis?.keyFactors).find((factor) => String(factor?.label || '').toLowerCase().includes('risk'));
  return typeof risk?.value === 'string' && risk.value.trim() ? risk.value.trim() : '';
}

function decorateAnalysis(analysis, { cached = false, event = null } = {}) {
  if (!analysis) return null;
  const decorated = cloneAnalysisData(analysis);
  const generatedAt = decorated._meta?.generatedAt || Date.now();
  const confidence = Number.parseInt(decorated.confidence, 10) || 0;

  decorated.disclaimer = decorated.disclaimer
    || 'AI-generated analysis based on available market context and model interpretation. Treat it as guidance, not certainty.';
  decorated._meta = {
    provider: 'EdgeIQ AI analysis',
    sourceType: 'generated_insight',
    generatedAt,
    cached,
    cacheTtlSec: Math.round(AI_TTL / 1000),
    eventId: event?.id || decorated._meta?.eventId || null,
    inputType: event?.id?.startsWith('manual_') ? 'manual_scenario' : 'market_event',
    competition: event?.comp || null,
    venue: event?.venue || null,
    confidenceBand: getConfidenceBand(confidence),
    uncertaintyNote: getUncertaintyNote(decorated),
    sourceAttribution: 'Generated by EdgeIQ using model inference and the inputs supplied to the analysis request.',
  };

  return decorated;
}

function safeArray(value) {
  return Array.isArray(value) ? value : [];
}

function shouldPersistAnalysis(event) {
  return !!event?.id && !String(event.id).startsWith('manual_');
}

function getSportContext(sport) {
  const contexts = {
    NBA: `NBA SPECIFIC CONTEXT — Key factors to analyse:
- Pace & efficiency: offensive/defensive rating, points per 100 possessions
- Home court advantage (NBA teams historically win ~60% at home)
- Back-to-back games and rest days (huge impact — teams on 0 rest days lose ~5% more)
- Star player availability & load management (top-5 players on each team are decisive)
- Recent 3-point shooting efficiency (hot/cold shooting streaks)
- Paint dominance vs perimeter attack matchup
- Referee tendencies (foul rate impact on star players)
- Conference record and divisional familiarity
- Clutch performance: record in games within 5 points in final 5 minutes
Use NBA stat terminology: PPG, APG, RPG, eFG%, TS%, Net Rating, +/-.
Reference current season stats and recent form from 2024-25 NBA season.`,
    AFL: `AFL SPECIFIC CONTEXT — Key factors to analyse:
- Clearance differential (most predictive AFL stat)
- Contested possessions and inside 50s
- Interstate travel fatigue (WAFL, Queensland teams)
- MCG specialists vs away records
- Key position matchups: tall forwards vs backlines
- Weather conditions (wind/rain heavily affects scoring)
- Recent scoring: average score and opponent average score conceded
Use AFL stat terminology: disposals, handballs, kicks, marks, clearances, inside 50s.`,
    NRL: `NRL SPECIFIC CONTEXT — Key factors to analyse:
- Completion rate and error count (critical in NRL)
- Post-State of Origin player fatigue/absence
- Home ground advantage (NRL is highly home-ground dependent)
- Key playmaker availability (halfback/five-eighth)
- Defensive line speed and completion rate
- Penalties and discipline
- NSWRL vs QRL representative commitments
Use NRL stat terminology: tries, line breaks, tackles made, errors, penalties.`,
    Soccer: `SOCCER SPECIFIC CONTEXT — Key factors to analyse:
- Clean sheet probability and defensive record
- Head-to-head at this specific venue
- Squad rotation and Europa/Champions League fatigue
- xG (expected goals) vs actual goals — is form sustainable?
- Set piece efficiency (corners, free kicks)
- Manager tactical matchup
- Home/away splits are dramatic in soccer
Use soccer analytics: xG, xGA, PPDA, possession %, shots on target.`,
    UFC: `UFC/MMA SPECIFIC CONTEXT — Key factors to analyse:
- Striking accuracy and takedown defence %
- Finish rate and method of victory tendencies
- Recent performance bonus history (activity/aggression)
- Camp and gym (training partner quality)
- Weight cut history and late notice replacements
- Reach and physical advantages
- Judges tendencies at this venue
Use MMA stats: significant strikes per minute, takedown %, submission attempts.`,
    Boxing: `BOXING SPECIFIC CONTEXT — Key factors to analyse:
- Power punching vs volume punching styles
- KO/TKO rate and chin durability
- Ring rust (time away from boxing)
- Promotional politics and judge bias concerns
- Weight class move history
- Trainer pedigree and camp quality
Use boxing stats: punches landed per round, knockdown ratio, reach, southpaw/orthodox matchup.`,
  };

  return contexts[sport] || '';
}

export function getCachedAnalysis(eventId) {
  return decorateAnalysis(aiCache[eventId]?.data || null, { cached: true });
}

export function hasFreshAnalysis(eventId) {
  return isFresh(aiCache, eventId, AI_TTL);
}

export async function deleteCachedAnalysis(eventId) {
  delete aiCache[eventId];
  await getRepository().removeAiCacheEntry(eventId);
  analysisLogger.info('analysis.cache.deleted', { eventId });
}

export async function restorePersistedAnalysisCache() {
  const restoredEntries = await getRepository().restoreAiCache();
  let restored = 0;

  for (const [id, entry] of Object.entries(restoredEntries)) {
    aiCache[id] = entry;
    restored += 1;
  }

  analysisLogger.info('analysis.cache.restored', { entryCount: restored });

  return restored;
}

export async function analyseMatch(event, playerMarkets = null) {
  if (!env.ANTHROPIC_API_KEY) return null;
  if (shouldPersistAnalysis(event) && isFresh(aiCache, event.id, AI_TTL)) {
    analysisLogger.debug('analysis.cache.hit', { eventId: event.id });
    return decorateAnalysis(aiCache[event.id].data, { cached: true, event });
  }

  if (aiInflight[event.id]) {
    analysisLogger.debug('analysis.inflight.dedup', { eventId: event.id });
    return aiInflight[event.id];
  }

  const promise = doAnalyseMatch(event, playerMarkets).finally(() => {
    delete aiInflight[event.id];
  });
  aiInflight[event.id] = promise;

  return promise;
}

async function doAnalyseMatch(event, playerMarkets = null) {
  try {
    const home = event.home;
    const away = event.away;
    const sport = event.sport;
    const oddsLine = `${home} @ ${event.homeOdds}, ${away} @ ${event.awayOdds}${event.drawOdds ? `, Draw @ ${event.drawOdds}` : ''}`;
    const recOptions = event.drawOdds ? `"${home}", "${away}", or "Draw"` : `"${home}" or "${away}"`;
    const favTeam = event.homeOdds <= event.awayOdds ? home : away;
    const dogTeam = event.homeOdds <= event.awayOdds ? away : home;
    const sportContext = getSportContext(sport);

    let playerSection = '';
    if (playerMarkets) {
      if (sport === 'AFL') {
        if (playerMarkets.firstGoal?.length) playerSection += `\nFIRST GOAL / ANYTIME GOAL SCORER OPTIONS: ${playerMarkets.firstGoal.join(', ')}\n`;
        if (playerMarkets.disposals?.length) playerSection += `DISPOSALS (20+/25+) PLAYER OPTIONS: ${playerMarkets.disposals.join(', ')}\n`;
      } else if (sport === 'NRL') {
        if (playerMarkets.tryscorers?.length) playerSection += `\nTRY SCORER OPTIONS: ${playerMarkets.tryscorers.join(', ')}\n`;
      } else if (sport === 'NBA') {
        if (playerMarkets.pointsPlayers?.length) playerSection += `\nPLAYER POINTS OPTIONS: ${playerMarkets.pointsPlayers.join(', ')}\n`;
      }
    }

    const prompt = `You are a sharp sports betting analyst covering Australian and international markets. Analyse this match and return ONLY a JSON object — no markdown, no explanation outside the JSON.

MATCH: ${home} vs ${away}
SPORT: ${sport}
ODDS: ${oddsLine}
${event.comp ? `COMPETITION: ${event.comp}\n` : ''}${event.venue ? `VENUE: ${event.venue}\n` : ''}${event.context ? `EXTRA USER CONTEXT: ${event.context}\n` : ''}${sportContext ? `\n${sportContext}\n` : ''}${playerSection}
Draw on your sports knowledge to produce SPECIFIC, REALISTIC analysis, but never invent facts. If you are not confident about an exact stat, lineup item, scoreline, or recent result, stay qualitative instead of guessing. Use actual numbers, player names, and historical references only when you can state them confidently.
Use calibrated language. Never imply certainty, guaranteed wins, or sure things. Frame the recommendation as a stronger side, lean, or edge, and acknowledge the key uncertainty where relevant.

Return this exact JSON structure with ALL fields filled in:

{
  "recommendation": <one of ${recOptions}>,
  "confidence": <integer 50-95>,
  "valueBet": <true if the recommended team's odds represent genuine value, false otherwise>,
  "summary": "<2-3 sentence punchy verdict that explains WHY this is the pick, referencing specific form or stats>",
  "form": {
    "home": "<${home} last 5 results e.g. W W L W W — with a specific note about their current momentum, scoring avg, or key players>",
    "away": "<${away} last 5 results e.g. L W W L W — with a specific note about their current momentum, scoring avg, or key players>"
  },
  "headToHead": "<Specific H2H record between these teams, e.g. '${home} have won 7 of the last 10 meetings. They won the most recent clash 22-14 in Round 18 last season.' Include actual recent results if known.>",
  "venueEdge": "<Specific venue/home court advantage or disadvantage, referencing the actual arena/stadium, home record this season, and any travel/scheduling factors for ${away}>",
  "keyFactors": [
    {"icon": "⚡", "label": "Key Reason", "value": "<The single most decisive factor — use sport-specific stats and player names>"},
    {"icon": "📊", "label": "Form Edge", "value": "<Specific form stat with numbers — scoring averages, recent results, efficiency metrics>"},
    {"icon": "🏟️", "label": "Venue / Schedule", "value": "<Home court/ground advantage with specific record, and any back-to-back or travel fatigue>"},
    {"icon": "⚠️", "label": "Risk", "value": "<Main risk to the pick — injury, player availability, hot opponent form, or statistical anomaly>"}
  ],
  "bettingAngle": "<One sharp betting insight referencing the specific odds above — e.g. line value, market inefficiency, or why the favourite/underdog price is correct or incorrect given specific stats.>",
  "props": {
    "ou": <AFL/NRL/NBA/Soccer only: "over" or "under" — your pick on the total points/goals market, null for UFC/Boxing>,
    "ouReason": "<10-15 words max explaining the over/under pick — scoring pace, defensive stats, weather, etc. null for UFC/Boxing>",
    "margin": <AFL only: your pick from exactly one of: "${favTeam} 1–39", "${favTeam} 40+", "${dogTeam} 1–39", "${dogTeam} 40+" — use the en-dash character, null for all other sports>,
    "btts": <Soccer only: "yes" or "no" — both teams to score, null for all other sports>,
    "mov": <UFC/Boxing only: e.g. "${home} by KO/TKO" or "${away} by Decision" or "${away} by Submission" — the most likely finish, null for other sports>,
    "dist": <UFC/Boxing only: "yes" or "no" — does the fight go the full distance, null for other sports>,
    "distReason": "<UFC/Boxing only: 10-15 words why it does/doesn't go the distance, null for other sports>"
  },
  "playerPicks": {
    "firstGoal": <AFL only if FIRST GOAL OPTIONS provided: exact player name from the list most likely to kick the first goal, null otherwise>,
    "anyGoal": <AFL only if FIRST GOAL OPTIONS provided: exact player name from the list most likely to kick 2+ goals (can differ from firstGoal), null otherwise>,
    "dis20": <AFL only if DISPOSALS OPTIONS provided: exact player name from the list most likely to record 20+ disposals, null otherwise>,
    "dis25": <AFL only if DISPOSALS OPTIONS provided: exact player name from the list most likely to record 25+ disposals (can differ from dis20), null otherwise>,
    "firstTry": <NRL only if TRY SCORER OPTIONS provided: exact player name from the list most likely to score the first try, null otherwise>,
    "anyTry": <NRL only if TRY SCORER OPTIONS provided: exact player name most likely to score anytime (can differ from firstTry), null otherwise>,
    "pts20": <NBA only if PLAYER POINTS OPTIONS provided: exact player name from the list most likely to score 20+ points, null otherwise>,
    "pts30": <NBA only if PLAYER POINTS OPTIONS provided: exact player name from the list most likely to score 30+ points (can differ from pts20), null otherwise>
  }
}`;

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 2000,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    const data = await response.json();
    if (data.error) {
      const message = data.error?.message || JSON.stringify(data.error);
      analysisLogger.error('analysis.upstream.error', {
        eventId: event.id,
        error: { name: 'AnthropicError', message },
      });
      if (message.includes('credit') || message.includes('billing')) {
        return { _error: 'credits', message: 'AI credits exhausted — top up at console.anthropic.com' };
      }
      return null;
    }

    const stopReason = data.stop_reason;
    if (stopReason === 'max_tokens') {
      analysisLogger.warn('analysis.response.truncated', { eventId: event.id, stopReason });
    }

    const raw = data.content?.[0]?.text || '';
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    const jsonStr = jsonMatch ? jsonMatch[0] : raw.replace(/```json|```/g, '').trim();

    let analysis;
    try {
      analysis = JSON.parse(jsonStr);
    } catch {
      let patched = jsonStr.replace(/,\s*$/, '');
      if ((patched.match(/"/g) || []).length % 2 !== 0) patched += '"';

      const openArrays = (patched.match(/\[/g) || []).length - (patched.match(/\]/g) || []).length;
      for (let index = 0; index < openArrays; index += 1) patched += ']';

      const openObjects = (patched.match(/\{/g) || []).length - (patched.match(/\}/g) || []).length;
      for (let index = 0; index < openObjects; index += 1) patched += '}';

      analysis = JSON.parse(patched);
      analysisLogger.warn('analysis.response.recovered_json', { eventId: event.id });
    }

    if (!analysis.recommendation || !analysis.confidence) {
      throw new Error('Missing required AI fields');
    }

    const decorated = decorateAnalysis(analysis, { cached: false, event });
    if (shouldPersistAnalysis(event)) {
      const entry = { data: decorated, ts: Date.now() };
      aiCache[event.id] = entry;
      getRepository()
        .saveAiCacheEntry(event.id, entry)
        .catch((error) => analysisLogger.error('analysis.cache.persist_failed', {
          eventId: event.id,
          error: { name: error.name, message: error.message },
        }));
    }
    analysisLogger.info('analysis.generated', {
      eventId: event.id,
      sport,
      confidence: decorated.confidence,
      recommendation: decorated.recommendation,
      recoveredJson: stopReason === 'max_tokens',
      cached: false,
      persisted: shouldPersistAnalysis(event),
    });

    return decorated;
  } catch (error) {
    analysisLogger.error('analysis.failed', {
      eventId: event.id,
      sport: event.sport,
      error: { name: error.name, message: error.message },
    });
    return null;
  }
}

export function queueAIAnalysis() {
  // Background pre-analysis intentionally disabled to preserve API credits.
}
