import { ALL_SPORTS, ODDS_BASE, ODDS_TTL } from '../config/constants.js';
import { env } from '../config/env.js';
import { logger } from '../lib/logger.js';
import { getRepository } from '../lib/repository/index.js';
import { getCachedAnalysis } from './analysis-service.js';
import { getRacingEvents } from './racing-service.js';
import { sleep } from '../utils/sleep.js';

const oddsCache = {};
let combinedOddsCache = { data: null, ts: 0 };
let oddsApiCreditsRemaining = null;
let combinedOddsMeta = { sports: {}, warnings: [], sources: [], generatedAt: 0 };
const oddsLogger = logger.child({ component: 'odds-service', provider: 'The Odds API' });

export function resetOddsServiceState() {
  for (const key of Object.keys(oddsCache)) {
    delete oddsCache[key];
  }
  combinedOddsCache = { data: null, ts: 0 };
  oddsApiCreditsRemaining = null;
  combinedOddsMeta = { sports: {}, warnings: [], sources: [], generatedAt: 0 };
}

function getFreshnessStatus(cacheAgeSec, ttlSec) {
  if (cacheAgeSec <= Math.round(ttlSec * 0.15)) return 'fresh';
  if (cacheAgeSec <= ttlSec) return 'cached';
  return 'stale';
}

function buildSourceMeta({
  provider,
  sourceType = 'verified_data',
  mode,
  asOf = Date.now(),
  cacheTtlSec = Math.round(ODDS_TTL / 1000),
  warning = '',
  projected = false,
}) {
  const cacheAge = Math.max(0, Math.round((Date.now() - asOf) / 1000));
  const freshnessStatus = getFreshnessStatus(cacheAge, cacheTtlSec);

  return {
    provider,
    sourceType,
    mode,
    cached: mode !== 'live_feed',
    projected,
    asOf,
    asOfIso: new Date(asOf).toISOString(),
    cacheAge,
    cacheTtl: cacheTtlSec,
    freshnessStatus,
    freshnessLabel: freshnessStatus === 'fresh'
      ? 'Fresh feed'
      : freshnessStatus === 'cached'
        ? `Cached ${Math.max(1, Math.round(cacheAge / 60))}m ago`
        : `Stale ${Math.max(1, Math.round(cacheAge / 60))}m old`,
    sourceAttribution: projected
      ? 'Generated by EdgeIQ from schedule assumptions and modelled fields.'
      : 'Verified market data supplied via The Odds API.',
    warning,
  };
}

function slimOddsEvents(events = []) {
  return events.map((event) => ({
    id: event.id,
    home_team: event.home_team,
    away_team: event.away_team,
    commence_time: event.commence_time,
    bookmakers: event.bookmakers?.slice(0, 1).map((bookmaker) => ({
      markets: bookmaker.markets?.filter((market) => market.key === 'h2h').map((market) => ({
        key: market.key,
        outcomes: market.outcomes.map((outcome) => ({ name: outcome.name, price: outcome.price })),
      })) || [],
    })) || [],
  }));
}

export async function restorePersistedOddsCache() {
  const persistedEntries = await getRepository().restoreOddsCache();
  let restored = 0;
  let oldestOddsTs = Infinity;
  const combinedData = {};
  const storedOddsKeys = Object.keys(persistedEntries);
  const restoredMeta = {};

  oddsLogger.info('odds.restore.start', { persistedSports: storedOddsKeys });

  for (const [sport, entry] of Object.entries(persistedEntries)) {
    const now = Date.now();
    const ageMin = entry?.ts ? Math.round((now - entry.ts) / 60000) : null;
    const slimData = slimOddsEvents(entry.data || []);
    const slimEntry = { data: slimData, ts: entry.ts };
    oddsCache[sport] = slimEntry;
    restoredMeta[sport] = buildSourceMeta({
      provider: 'The Odds API',
      mode: 'cached_feed',
      asOf: entry.ts,
    });
    combinedData[ALL_SPORTS.find((item) => item.key === sport)?.label || sport] = slimData;
    if (entry.ts < oldestOddsTs) oldestOddsTs = entry.ts;
    restored += 1;
    oddsLogger.debug('odds.restore.entry', {
      sport,
      cacheAgeMin: ageMin,
      eventCount: slimData.length,
    });
    getRepository()
      .saveOddsCacheEntry(sport, slimEntry)
      .catch((error) => oddsLogger.error('odds.cache.persist_failed', {
        sport,
        operation: 'normalize_restore',
        error: { name: error.name, message: error.message },
      }));
  }

  if (restored === ALL_SPORTS.length) {
    combinedOddsCache = { data: combinedData, ts: oldestOddsTs };
  }
  combinedOddsMeta = {
    sports: restoredMeta,
    warnings: [],
    sources: Object.entries(restoredMeta).map(([sport, meta]) => ({ label: ALL_SPORTS.find((item) => item.key === sport)?.label || sport, ...meta })),
    generatedAt: Date.now(),
  };

  return { restored, total: ALL_SPORTS.length };
}

async function fetchOdds(sport, regions = 'au') {
  if (oddsCache[sport] && Date.now() - oddsCache[sport].ts < ODDS_TTL) {
    oddsLogger.debug('odds.cache.hit', {
      sport,
      cacheAgeSec: Math.round((Date.now() - oddsCache[sport].ts) / 1000),
    });
    return oddsCache[sport].data;
  }

  oddsLogger.debug('odds.cache.miss', { sport, regions });

  const response = await fetch(`${ODDS_BASE}/sports/${sport}/odds/?apiKey=${env.ODDS_API_KEY}&regions=${regions}&markets=h2h&oddsFormat=decimal`);
  if (!response.ok) throw new Error(`Odds API ${response.status}`);

  const remaining = response.headers.get('x-requests-remaining');
  const used = response.headers.get('x-requests-used');
  if (remaining !== null) {
    oddsApiCreditsRemaining = Number.parseInt(remaining, 10);
    oddsLogger.info('odds.fetch.success', {
      sport,
      creditsUsed: used ? Number.parseInt(used, 10) : null,
      creditsRemaining: oddsApiCreditsRemaining,
    });
  }

  const data = await response.json();
  const slimData = slimOddsEvents(data);
  const entry = { data: slimData, ts: Date.now() };

  oddsCache[sport] = entry;
  getRepository()
    .saveOddsCacheEntry(sport, entry)
    .catch((error) => oddsLogger.error('odds.cache.persist_failed', {
      sport,
      operation: 'save_fetch',
      error: { name: error.name, message: error.message },
    }));

  return slimData;
}

export async function fetchAllOdds() {
  if (combinedOddsCache.data && Date.now() - combinedOddsCache.ts < ODDS_TTL) {
    oddsLogger.debug('odds.combined_cache.hit', {
      cacheAgeSec: Math.round((Date.now() - combinedOddsCache.ts) / 1000),
    });
    return combinedOddsCache.data;
  }

  const results = {};
  const sportMeta = {};
  const warnings = [];
  for (let index = 0; index < ALL_SPORTS.length; index += 1) {
    const sport = ALL_SPORTS[index];
    if (index > 0) await sleep(300);
    try {
      results[sport.label] = await fetchOdds(sport.key, sport.regions || 'au');
      sportMeta[sport.key] = buildSourceMeta({
        provider: 'The Odds API',
        mode: oddsCache[sport.key]?.ts && Date.now() - oddsCache[sport.key].ts < 10_000 ? 'live_feed' : 'cached_feed',
        asOf: oddsCache[sport.key]?.ts || Date.now(),
      });
    } catch (error) {
      oddsLogger.warn('odds.fetch.failed', {
        sport: sport.key,
        error: { name: error.name, message: error.message },
        hasCachedFallback: !!oddsCache[sport.key]?.ts,
      });
      results[sport.label] = oddsCache[sport.key]?.data || [];
      sportMeta[sport.key] = buildSourceMeta({
        provider: 'The Odds API',
        mode: oddsCache[sport.key]?.ts ? 'cached_fallback' : 'unavailable',
        asOf: oddsCache[sport.key]?.ts || Date.now(),
        warning: oddsCache[sport.key]?.ts
          ? `Using cached ${sport.label} prices because the live odds request failed.`
          : `No ${sport.label} prices are available right now.`,
      });
      warnings.push({
        type: oddsCache[sport.key]?.ts ? 'stale-cache' : 'odds-unavailable',
        severity: 'warning',
        title: oddsCache[sport.key]?.ts ? `${sport.label} showing cached data` : `${sport.label} unavailable`,
        message: sportMeta[sport.key].warning,
      });
    }
  }

  combinedOddsCache = { data: results, ts: Date.now() };
  combinedOddsMeta = {
    sports: sportMeta,
    warnings,
    sources: ALL_SPORTS.map((sport) => ({ label: sport.label, ...(sportMeta[sport.key] || {}) })),
    generatedAt: Date.now(),
  };
  const savedSports = Object.keys(oddsCache);
  if (savedSports.length > 0) {
    oddsLogger.info('odds.persist.summary', {
      sportCount: savedSports.length,
      sports: savedSports,
    });
  }

  return results;
}

export function getOddsUsage() {
  const cacheAge = combinedOddsCache.ts ? Math.round((Date.now() - combinedOddsCache.ts) / 1000) : null;
  const nextRefresh = cacheAge !== null ? Math.max(0, Math.round((ODDS_TTL / 1000) - cacheAge)) : 0;

  return {
    creditsRemaining: oddsApiCreditsRemaining,
    cacheAge,
    nextRefresh,
    cacheTTLHours: ODDS_TTL / 3600000,
    hasCachedData: !!combinedOddsCache.data,
  };
}

export async function buildOddsEvents() {
  const raw = await fetchAllOdds();
  const sportLabels = { afl: 'AFL', nrl: 'NRL', soccer_al: 'Soccer', soccer_epl: 'Soccer', ufc: 'UFC', boxing: 'Boxing', nba: 'NBA' };
  const labelToKey = Object.fromEntries(ALL_SPORTS.map((sport) => [sport.label, sport.key]));
  const events = [];
  const warnings = [...(combinedOddsMeta.warnings || [])];

  for (const [key, eventList] of Object.entries(raw)) {
    const sourceKey = labelToKey[key];
    const dataMeta = combinedOddsMeta.sports[sourceKey] || buildSourceMeta({
      provider: 'The Odds API',
      mode: 'cached_feed',
      asOf: combinedOddsCache.ts || Date.now(),
    });
    for (const event of eventList || []) {
      const h2h = event.bookmakers?.[0]?.markets?.find((market) => market.key === 'h2h');
      if (!h2h) continue;

      const home = h2h.outcomes.find((outcome) => outcome.name === event.home_team);
      const away = h2h.outcomes.find((outcome) => outcome.name === event.away_team);
      const draw = h2h.outcomes.find((outcome) => outcome.name === 'Draw');
      if (!home || !away) continue;

      const aiData = getCachedAnalysis(event.id) || null;
      events.push({
        id: event.id,
        sport: sportLabels[key] || key,
        home: event.home_team,
        away: event.away_team,
        homeOdds: home.price,
        awayOdds: away.price,
        drawOdds: draw?.price || null,
        commenceTime: event.commence_time,
        aiReady: !!aiData,
        dataMeta,
        analysisMeta: aiData?._meta || null,
        ...(aiData || {}),
      });
    }
  }

  const racingPayload = await getRacingEvents();
  warnings.push(...(racingPayload.warnings || []));
  for (const event of racingPayload.events || []) {
    const favourite = event.runners[0];
    const racingSport = event.sport_key === 'greyhound_racing_au' ? 'Greyhound' : 'Horse Racing';
    events.push({
      id: event.id,
      sport: racingSport,
      home: favourite.name,
      away: `R${event.raceNumber} ${event.venue}`,
      homeOdds: favourite.odds,
      awayOdds: event.runners[1]?.odds || null,
      drawOdds: null,
      commenceTime: event.commence_time,
      aiReady: false,
      venue: event.venue,
      comp: event.comp,
      distance: event.distance,
      distanceLabel: event.distanceLabel || `${event.distance}m`,
      raceNumber: event.raceNumber,
      runners: event.runners,
      isRacing: true,
      isLiveData: event.isLiveData || false,
      raceName: event.raceName || '',
      going: event.going || '',
      prizeTotal: event.prizeTotal || '',
      state: event.state || '',
      dataMeta: event.dataMeta || null,
    });
  }

  const cacheAge = combinedOddsCache.ts ? Math.round((Date.now() - combinedOddsCache.ts) / 1000) : 0;
  const nextRefresh = Math.max(0, Math.round((ODDS_TTL - (Date.now() - combinedOddsCache.ts)) / 1000));
  const freshnessStatus = getFreshnessStatus(cacheAge, Math.round(ODDS_TTL / 1000));

  return {
    success: true,
    events,
    cacheAge,
    nextRefresh,
    cacheTTL: ODDS_TTL / 1000,
    creditsRemaining: oddsApiCreditsRemaining,
    generatedAt: Date.now(),
    asOf: combinedOddsCache.ts || Date.now(),
    freshnessStatus,
    freshnessLabel: freshnessStatus === 'fresh'
      ? 'Fresh market snapshot'
      : freshnessStatus === 'cached'
        ? `Cached snapshot from ${Math.max(1, Math.round(cacheAge / 60))}m ago`
        : `Stale snapshot from ${Math.max(1, Math.round(cacheAge / 60))}m ago`,
    sources: [
      ...(combinedOddsMeta.sources || []),
      ...(racingPayload.sourceSummary || []),
    ],
    warnings,
  };
}
